---
title: "EY90 Analysis"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(DescTools) # AUC calculation
library(ggpubr) # P values


df <- read_excel("~/Documents/Experiments/2.17.26 EY90 G192 mCherry.xlsx", 
    sheet = "Sheet1")
```

```{r}

newdf<- df %>%
  group_by(ID) %>%
  summarize(across(A1:G11, max)) 

newdf1<- newdf %>%
  slice(seq(from = 1, to = n(), by = 2))
newdf2 <- newdf %>%
  slice(seq(from = 2, to = n(), by = 2))

min <-c(0,18.5,37,55.5,74,92.5,111,129.5,148,166.5,185,203.5,222,240.5,259,277.5,296,314.5,333,351.5,370,388.5,407,425.5,444,462.5,481,499.5,518,536.5,555,573.5,592,610.5,629,647.5,666,684.5,703,721.5,740,758.5,777,795.5,814,832.5,851,869.5,888,906.5,925,943.5,962,980.5,999,1017.5,1036) 

i <- cbind(newdf1,min)
j <- cbind(newdf2,min)
```

```{r Lum}

p <- ggplot(i, aes(x=min)) + 
  geom_line(aes(y = A1),color="steelblue") + 
  geom_line(aes(y = A3),color="steelblue") + 
  geom_line(aes(y = A5),color="black") + 
  geom_line(aes(y = C1),color="red") + 
  geom_line(aes(y = C3),color="red") + 
  geom_line(aes(y = C5),color="gray") + 
  geom_line(aes(y = E1),color="red") + 
  geom_line(aes(y = E3),color="red") +
  geom_line(aes(y = E5),color="gray") + 
  geom_line(aes(y = G1),color="red") + 
  geom_line(aes(y = G3),color="red") +
  geom_line(aes(y = G5),color="black") + 
  labs(title="EY90 Male Lum",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY90 MLum.png")

   p <- ggplot(i, aes(x=min)) +  
  geom_line(aes(y = A7), color="steelblue") + 
  geom_line(aes(y = A9), color="steelblue") +
  geom_line(aes(y = A11), color="black") + 
  geom_line(aes(y = C7), color="steelblue") +
  geom_line(aes(y = C9), color="red") +
  geom_line(aes(y = C11), color="black") + 
  geom_line(aes(y = E7), color="steelblue") +
  geom_line(aes(y = E9), color="red") +
  geom_line(aes(y = G7), color="steelblue") +
  geom_line(aes(y = G9), color="steelblue") +
labs(title="EY90 Female Lum",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY90 FLum.png")
```

```{r Fluor}
colors <- c("Female" = "red","Control Female" = "black")
p <- ggplot(j, aes(x=min)) + 
  geom_line(aes(y = A1),color="steelblue") + 
  geom_line(aes(y = A3),color="steelblue") + 
  geom_line(aes(y = A5),color="black") + 
  geom_line(aes(y = C1),color="red") + 
  geom_line(aes(y = C3),color="red") + 
  geom_line(aes(y = C5),color="gray") + 
  geom_line(aes(y = E1),color="red") + 
  geom_line(aes(y = E3),color="red") +
  geom_line(aes(y = E5),color="gray") + 
  geom_line(aes(y = G1),color="red") + 
  geom_line(aes(y = G3),color="red") +
  geom_line(aes(y = G5),color="black") + 
  labs(title="EY90 Male Fluor",
        x ="Time (min)", y = "Fluorescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY90 MFluor.png")

   p <- ggplot(j, aes(x=min)) +  
  geom_line(aes(y = A7, color="Female")) + 
  geom_line(aes(y = A9, color="Female")) +
  geom_line(aes(y = A11, color="Control Female")) + 
  geom_line(aes(y = C7, color="Female")) +
  geom_line(aes(y = C9, color="Female")) +
  geom_line(aes(y = C11, color="Control Female")) + 
  geom_line(aes(y = E7, color="Female")) +
  geom_line(aes(y = E9, color="Female")) +
  geom_line(aes(y = G7, color="Female")) +
  geom_line(aes(y = G9, color="Female")) +
labs(title="Dipt>mCherry",
        x ="Time (min)", y = "Fluorescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY90 Poster.png")
```


```{r}

my_vec <- numeric()

for (col in i) {
    a <- AUC(min, col, method = c("trapezoid"))
    my_vec <- c(my_vec, a)
}

print(my_vec)

df <- data.frame(dose=c("Male","Male","CM","Female","Female","CF","Male","Male","CM","Female","Female","CF","Male", "Male", "CM","Female","Female","Male","Male","CM","Female","Female"),
    len=c(36694.75, 34373.00,  15706.50,  23661.50,  33827.25,  14883.25,  66516.75,
121073.25,  14291.25,  25927.75,  52706.50,  14605.75, 101047.00,  54686.00,  14781.50,
53335.50,  51578.00,  88827.75,  67691.50,  14457.75,  41532.50,  24392.25))

my_comparisons <- list( c("Female", "CF"), c("Male", "CM"))
p <- ggplot(df, aes(x=dose, y=len)) +
geom_bar(stat="summary", 
           fun=mean,
           aes(fill=dose)) +
  geom_point(position = position_jitter(width = 0.2), color = "black")+
  stat_compare_means(comparisons = my_comparisons)+
  #geom_signif(comparisons = my_comparisons, map_signif_level=TRUE)+
  labs(title="EY90 Lum AUC",
        x ="Condition", y = "Area Under Curve", color = "Legend")+
    scale_color_manual(values = colors)
p

#ggsave("EY90 LAUC.png")

```

```{r}
my_vec <- numeric()

for (col in j) {
    a <- AUC(min, col, method = c("trapezoid"))
    my_vec <- c(my_vec, a)
}

print(my_vec)

df <- data.frame(dose=c("Male","Male","CM","Female","Female","CF","Male","Male","CM","Female","Female","CF","Male", "Male", "CM","Female","Female","Male","Male","CM","Female","Female"),
    len=c(15993.25,  10628.25,   7575.75,  12413.50,  16085.75,   8713.50,  13551.25,
13292.25,   7973.50,  13218.25,  13310.75,   9250.00,  12348.75,  19850.50,  10258.25,
11978.75,  13754.75,  14689.00,  16326.25,   9379.50,  13181.25,  15632.50))

my_comparisons <- list( c("Female", "CF"), c("Male", "CM"))
p <- ggplot(df, aes(x=dose, y=len)) +
geom_bar(stat="summary", 
           fun=mean,
           aes(fill=dose)) +
  geom_point(position = position_jitter(width = 0.2), color = "black")+
  stat_compare_means(comparisons = my_comparisons)+
  labs(title="EY90 Fluor AUC",
        x ="Condition", y = "Area Under Curve", color = "Legend")+
    scale_color_manual(values = colors)
p


#ggsave("EY90 FAUC.png")
```